### ISSUE TITLE
[ISSUE]:  res increases rapidly ingame

### ISSUE THREAD

**Issue by user180706** [w-okada/voice-changer#1373]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.18a.zip

### Operational System

Windows 10

### GPU

AMD Radeon RX 7900 XTX

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

works fine when I'm talking but when I open a game
and try to talk, res goes up really high. I checked GPU and CPU usage but it never goes above 70%.
I tried to make the chunk higher etc...
nothing helped

### Logs on console

Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 5
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:CPU-DML)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
2024-10-08 19:41:53.2899610 [W:onnxruntime:, session_state.cc:1169 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-10-08 19:41:53.2941079 [W:onnxruntime:, session_state.cc:1171 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x000001C1CA83FF10>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000001C1CA8C08B0>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x000001C1CA8C0910>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings extraConvertSize:4096
[Voice Changer][RVC]: update_settings enableServerAudio:0
[Voice Changer][RVC]: update_settings serverInputDeviceId:2
[Voice Changer][RVC]: update_settings serverOutputDeviceId:8
[Voice Changer][RVC]: update_settings serverAudioSampleRate:16000
[Voice Changer][RVC]: update_settings serverReadChunkSize:192
[Voice Changer][RVC]: update_settings modelSlotIndex:1728409003005
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2024-10-08 19:41:55] connet sid : 8-9JCnRurv1FPE28AAAC
[2024-10-08 19:41:55] connet sid : 9tRw_m0rpbzVTElUAAAD

**Comment by Kuuko-fokkusugaru** [comment]
RVC it's a very demanding software. Trying to run it among a demanding game will slow down RVC to, sometimes, extreme delayed sound or even broken one. RVC is intended to be used on a secondary computer while gaming on a primary one, that's why you have the server option and why you can access to it through a regular browser using the given local IP address.
That said, you can try lowering your game requisites by lowering it's quality and see if that helps enough. But, if you really want to game and use RVC at the same time, you should look into getting a nvidia 3080, 3090, 4080, or 4090. Ideally, only a 4090 would allow you to play most games while using RVC as long as you don't try to play all of them at 4K and more than 120fps.

**Comment by user180706** [comment]
Ah ok thx. 
But how do i connect my PCs?

**Comment by Kuuko-fokkusugaru** [comment]
When you run RVC on one computer and want to use it on another different computer, first make sure that both are connected to the same network (same router, WI-FI, etc). Start RVC but use the start_https.bat instead of start_http.bat. After it starts, the console will give you an IP address with a port. Write that address and the port on your other computer's browser like Chrome then you will see RVC UI right inside your browser. Now you can set the settings as desired, upload the voice model, etc. It will work similarly to when you run it on the same computer as the game except that the UI will now be on your browser and you may need to keep it open for RVC to work. That's all.

**Comment by user180706** [comment]
should I start start_https on my main pc where i  game?

**Comment by Kuuko-fokkusugaru** [comment]
no, you start the software on your secondary PC where you will NOT game

**Comment by user180706** [comment]
I seem to be doing something wrong. The browser says website not available. I copy https://<IP>:<PORT>/ and what is written underneath. Is that right or completely wrong?

**Comment by user180706** [comment]
I managed it but only with v2. only v1 doesn't work

**Comment by Kuuko-fokkusugaru** [comment]
> I managed it but only with v2. only v1 doesn't work

They both use the same ip but different ports

**Comment by user180706** [comment]
everything works fine but you can't hear me in games or in discord. I'm still using VB- Virtual Audio Cable just like before. I've downloaded VB Cabel on both PCs. Why doesn't it work?

**Comment by Kuuko-fokkusugaru** [comment]
You only need virtual cable on your main computer where you open RVC through browser and not running RVC software.
I recommend uninstalling vb cable and installing virtual audio cable (VAC).

A screenshot of your settings would greatly help on seeing where the issue may be.

**Comment by user180706** [comment]
![bild 1](https://github.com/user-attachments/assets/a4c3bb1b-c390-4dee-b980-7aeccd3f6304)
![bild 2](https://github.com/user-attachments/assets/319e8277-b08c-4897-8256-2712f37c691d)
![bild 3](https://github.com/user-attachments/assets/6111b4ea-2206-4890-a4c2-537488f4d696)
![bild 4](https://github.com/user-attachments/assets/dd6bed93-5b35-45a7-9971-ef8dc3e02d7e)

everything works well even v1 but you just can't hear me in discord

**Comment by Kuuko-fokkusugaru** [comment]
Do not use server mode.
Server mode means that the input and output are the ones on the computer running RVC.
Client mode means that the input and output are the ones on the main computer that you will use for games, discord, etc.
So if you want to use the microphone and headset from the computer that you will use to play games and for Discord, then you need to leave it in client mode. You will notice that the input and output devices will change accordingly.

**Comment by user180706** [comment]
![bild 5](https://github.com/user-attachments/assets/9a834d36-745b-49f7-bdfa-13e4b063fad4)

but then I can't select a microphone etc.

**Comment by user180706** [comment]
any ideas to solve this?

**Comment by Kuuko-fokkusugaru** [comment]
Since you are running it from a browser, make sure to give the browser permission to access your input devices. I recommend Chrome, it works very well. Also make sure that your microphone and headset are connected to the same computer of course.

Computer A: runs RVC
Computer B: runs browser, games, discord, etc, connect microphone, headset, etc

**Comment by Kuuko-fokkusugaru** [comment]
You could also connect your microphone to the computer A but if it's a headset you will have issues trying to hear computer B.
Also take into account that you have to run start_https.bat on the computer A (not start_http.bat). You don't need to setup any input or output in the computer A because everything will be setup in the browser from computer B. This includes VAC too.

**Comment by user180706** [comment]
ahhh yes my microphone was blocked. thank you very much it worked. but I have a question. I solved my problem in a different way and wanted to know which variant I should use.
what I did: 
Main PC gaming etc. B PC voice changer.
I started start_http.bat and connected my two PCs via AUX cable.
There was some noise at first, but I was able to fix it with a Ground Loop Noise Isolator for 5 euros.
Both variants sounded about the same.
Which should I use?

**Comment by Kuuko-fokkusugaru** [comment]
The simplest way it's just to use RVC computer only for RVC and the main computer for everything else including mic and VAC. Of course, you can do as you did and just use the whole RVC computer as a mic but I'd feel it would be way easier and more practical the other way. Because then you wouldn't have issues using the same headset to listen and speak in the main computer. RVC can't benefit from a good mic so having a mic only for the RVC computer wouldn't actually change or add any quality. If your headset already has a mic, using the suggested setup, you will avoid any cables or issues connecting devices and using them on every app.
But that's up to you. As long as it works, that's fine. One advantage of using the RVC computer as server with the mic connected there is that, depending on the driver mode selected to connect the mic, you can reduce the delay a bit.

**Comment by user180706** [comment]
I have a standalone microphone, so not with a headset. and VAC costs about 33 euros... I don't know if it's worth it.

**Comment by Kuuko-fokkusugaru** [comment]
VAC is free...

**Comment by user180706** [comment]
you man this website right? https://vac.muzychenko.net/en/ 
![bild 6](https://github.com/user-attachments/assets/423d9f79-81fb-4fac-864d-e986f552280d)
and in the free version you constantly hear a voice saying trial

**Comment by Kuuko-fokkusugaru** [comment]
You are downloading the trial of the full version instead of the lite free version.
Scroll down.

**Comment by user180706** [comment]
![bild 7](https://github.com/user-attachments/assets/328fa5dd-e2b8-44da-b5d3-ed442e471c56)

you mean this one ?

**Comment by Kuuko-fokkusugaru** [comment]
Yes

**Comment by user180706** [comment]
thank you very much

**Comment by user180706** [comment]
thank you very much
