### ISSUE TITLE
[ISSUE]: Im fine with others but when started the rvc models that i downloaded it increase the res

### ISSUE THREAD

**Issue by Hafeyol** [w-okada/voice-changer#1398]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.18a

### Operational System

windows 10

### GPU

rx 580

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

the response time increase when im trying other rvc models besides the basic one that im using and please let me know if my hardware issues or others and im a beginner please teach me steps by steps

### Application Screenshot

![image](https://github.com/user-attachments/assets/8e359704-3dfd-48ed-8c21-6a49edd8dff4)

### Logs on console

[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings serverReadChunkSize:192
[Voice Changer][RVC]: update_settings extraConvertSize:4096
[Voice Changer][RVC]: update_settings f0Detector:rmvpe_onnx
[Voice Changer][RVC]: update_settings modelSlotIndex:1730927594004
[Voice Changer] warming up... generating sola buffer.

**Comment by Kuuko-fokkusugaru** [comment]
The main difference between the included models and, possibly, downloaded ones is that the included models are in onnx format instead of pth format. There is an "export to onnx" button next to the "save settings" button. Export your model as onnx and add it to RVC. Let's see if that makes the res comparable to that of the included models.

By the way, for reference, try to include a full screenshot of RVC instead of a cropped portion without any information. There are many settings that could have a direct impact on the res processing time but they aren't visible on the screenshot at all.

**Comment by Hafeyol** [comment]
Yeah it worked flawlessly thank you so much as for reference if I ever having issues will include proper reference thank you so much

**Comment by Hafeyol** [comment]
worked

**Comment by Kuuko-fokkusugaru** [comment]
Yay! Glad to hear that!
