### ISSUE TITLE
[ISSUE]: Working Offline Without Error

### ISSUE THREAD

**Issue by serahBill** [w-okada/voice-changer#1422]
### Voice Changer Version

win_onnxgpu_cuda_v.1.5.3.18a

### Operational System

windows 10

### GPU

rtx 3060ti

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

all, once click on the gui it says cannot load "Voice Focus Estimator"

### Issue Description

Dear all,
i want to show my students in the class how it works.
but there is no internet in the class.
it is working on my pc online.
when i copy the model-dir folder and pretrained folder to the offline pc. it shows an error cannot load "Voice Focus Estimator"
what to do so i  can make it work offline without errors?
Thank you

### Logs on console

nothing

**Comment by exciar** [comment]
![image](https://github.com/user-attachments/assets/9d80f1d9-8dc8-4019-99aa-7d825d3115a1)
it works on mine without internet

try launching it via http.bat

**Comment by serahBill** [comment]
can you tell me the steps please?

**Comment by Kuuko-fokkusugaru** [comment]
Download the software and decompress it in a new folder inside of the root of the C drive.
Open the software with start_http.bat and wait for every file to download and the UI to open.
Once you have done that, close the software and open it again to make sure that it's working.
Now you can copy the whole folder inside of the C drive containing the software and copy to the offline computer exactly in the same location. Now the software should work just fine since all the necessary files are already downloaded and the directories are the same between the two computers. RVC only requires Internet connection the first time to download the necessary files.

**Comment by serahBill** [comment]
it worked thank you!
