### ISSUE TITLE
start_https.bat

### ISSUE THREAD

**Issue by straight-tamago** [w-okada/voice-changer#228]
start_https.batを起動して、RVC（それ以外も）を選択するとエラーが出ます。

start_http.batだとlocalhostのみで機能します。ipで開くと、画面が真っ白です。
コンソールには「Uncaught ReferenceError: AudioWorkletNode is not defined」

![C80C198A-4C19-4394-9CFC-F5324BF804EF](https://github.com/w-okada/voice-changer/assets/121408851/4aecfefe-7aaf-4a50-ac1c-df3d65f96dac)

**Comment by straight-tamago** [comment]
Chromeにするとうまくいきました。

**Comment by w-okada** [comment]
報告ありがとうございます。現在ブラウザはChromeのみ動作確認しております。
使用でございますのでcloseします。もしほかのブラウザのサポートが必要であれば、新たにissueを上げてください。
（対応するかはわかりませんが。）

**Comment by kronkinatorix** [comment]
I have this same errorr. It happens on Chrome / chromium on desktop / mobile. I'm able to open the page and the server receives a successful GET request but the page won't load with  

Uncaught ReferenceError: AudioWorkletNode is not defined

being the only useful piece of info it seems I can find. 

I've tried reinstalls of the latest version, as well as clean install with the last 3 releases. It was working fine a day ago and to the best of my knoweldge I didn't change anything. I can access the server pc ON the server at 0.0.0.0:port and at 127:0.0.1:port btu I can't access it from lan anymore, likely due to the above rror. I also can't access the server ON the server at the server's ip:portforvoicechanger(not litera)
