### ISSUE TITLE
Grunting sounds, completely garbled

### ISSUE THREAD

**Issue by slickery11234** [w-okada/voice-changer#340]
### Issue Type

Bug Report

### vc client version number

1.5.3.5

### OS

Windows 11

### GPU

3060 ti

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

crepe

### Situation

No matter what model i use, it makes a lot of weird sounds that are not similar to what I say at all. I have changed and reset every setting nothing has fixed it, I have no clue why its doing this. Ive also reinstalled nothing fixed it.

**Comment by FightingBlaze** [comment]
Same, I tried two different drives and no luck. Though using cdrive seemed to make it kinda get close but then nothing.

**Comment by w-okada** [comment]
show me log on terminal

**Comment by FightingBlaze** [comment]
> 

C:\Users\thoma\Desktop\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/checkpoint_best_legacy_500.onnx     --content_vec_500_onnx_on false     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    Voice Changerを起動しています。
++[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 0
................RVC
Preparing your application. Please wait...
(node:11240) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
2023-07-02 18:07:11 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-07-02 18:07:11 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-07-02 18:07:11 | INFO | faiss.loader | Loading faiss.
2023-07-02 18:07:12 | INFO | faiss.loader | Successfully loaded faiss.
[Voice Changer] [RVC] Creating instance
[Voice Changer] [RVC] Initializing...
inferencerTypeinferencerTypeinferencerTypeinferencerType onnxRVC
2023-07-02 18:07:13.6863193 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-07-02 18:07:13.6923317 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
Preparing your application. Please wait...
(node:11240) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] generate new embedder. (no embedder)
Preparing your application. Please wait...
(node:11240) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] Loading index...
GENERATE INFERENCER <voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x000001492E439240>
GENERATE EMBEDDER <voice_changer.RVC.embedder.FairseqHubert.FairseqHubert object at 0x0000014956C1C7F0>
GENERATE PITCH EXTRACTOR <voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x00000149FB5A18A0>
[Voice Changer] [RVC] Initializing... done
VoiceChanger Initialized (GPU_NUM:1, mps_enabled:False)
[Voice Changer][RVC]: update_settings silentThreshold 0.001
[Voice Changer][RVC]: update_settings modelSlotIndex 1688167744000
[Voice Changer][RVC]: update_settings silentThreshold 0.001
 [INFO] [DSH]  voice-changer-native-client.exe
 [INFO] [DSH]  Creating WndMsg Listener Window
 [INFO] [DSH]  Get number of capabilities
 [INFO] [DSH]  Get stream caps: 0
 [INFO] [DSH]  Get stream caps: 1
 [INFO] [DSH]  Get stream caps: 2
 [INFO] [DSH]  Get stream caps: 3
 [INFO] [DSH]  Get stream caps: 4
 [INFO] [DSH]  Get stream caps: 5
 [INFO] [DSH]  Get stream caps: 6
 [INFO] [DSH]  Get stream caps: 7
 [INFO] [DSH]  Get stream caps: 8
 [INFO] [DSH]  Get stream caps: 9
 [INFO] [DSH]  Get stream caps: 10
 [INFO] [DSH]  Get stream caps: 11
 [INFO] [DSH]  Get stream caps: 12
 [INFO] [DSH]  Get stream caps: 13
 [INFO] [DSH]  Get stream caps: 14
 [INFO] [DSH]  Get stream caps: 15
 [INFO] [DSH]  Get stream caps: 16
 [INFO] [DSH]  Get stream caps: 17
 [INFO] [DSH]  Get stream caps: 18
 [INFO] [DSH]  Get stream caps: 19
 [INFO] [DSH]  Get stream caps: 20
 [INFO] [DSH]  Get stream caps: 21
 [INFO] [DSH]  Get stream caps: 22
 [INFO] [DSH]  Get stream caps: 23
 [INFO] [DSH]  Get stream caps: 24
 [INFO] [DSH]  Get stream caps: 25
 [INFO] [DSH]  Get stream caps: 26
 [INFO] [DSH]  Get stream caps: 27
 [INFO] [DSH]  Get stream caps: 28
 [INFO] [DSH]  Get stream caps: 29
 [INFO] [DSH]  Get stream caps: 30
 [INFO] [DSH]  Get stream caps: 31
 [INFO] [DSH]  Get stream caps: 32
 [INFO] [DSH]  Destroying parent object
 [INFO] [DSH]  Destroying WndMsg Listener Window
 [INFO] [DSH]  Destroyed window
 [INFO] [DSH]  Unregistered window class
[2023-07-02 18:07:22] connet sid : Cqkp7Tm9Haf-j_hFAAAB
[2023-07-02 18:07:22] connet sid : h2Ow7pE3XA8qQU9kAAAD
[Voice Changer] update configuration: f0Detector crepe
[Voice Changer][RVC]: update_settings f0Detector crepe
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.

**Comment by w-okada** [comment]
No error found in your log. I have no idea why your voice is not converted.

**Comment by FightingBlaze** [comment]
Any settings or files or even file updates you would recommend that might fix it?

**Comment by w-okada** [comment]
https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md

**Comment by FightingBlaze** [comment]
Bro the literal step that has my issue says: 

"Q2. The voice is not being converted.

A2. Refer to this and identify where the problem lies, and consider a solution."
