### ISSUE TITLE
Pipeline has been deleted/index not found

### ISSUE THREAD

**Issue by JasondaUltima** [w-okada/voice-changer#670]
### Issue Type

Bug Report, Question

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12

### OS

Windows 11

### GPU

AMD Ryzen 3  3250U with Radeon Graphics

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch, ONNX

### Situation

I'm trying to use the base voices available but

1. It doesn't register my voice input no matter what I try
2. It keeps saying "Index file not found" and "Pipeline has been deleted"  which I don't know what that means or how to fix
3. The GPU Section is NOT a drop down menu like I have seen in multiple Tutorials instead its
"GPU (dml)"  With a couple of options like small boxes labeled "cpu", "gpu 1-3"

How do I get the program to work properly?

### logs on terminal

FF912BC2FFB: (caller: 00007FF912BC2D81) Exception(203) tid(7928)  C0262002 Specified display adapter handle is invalid. When using ['DmlExecutionProvider']

Falling back to ['CPUExecutionProvider'] and retrying.
[Voice Changer]   loading index...
[Voice Changer]   Index file is not found
Pipeline has been deleted

**Comment by Eidenz** [comment]
1/2: Index file not found, did you download a custom RVC model without an index file? Usually, when you get an RVC model online you should have two files: a ".pth" and a ".index".

3: You downloaded the directML version (MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12) instead of the Cuda only version (MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12).
That's normal you're not seeing your GPU name in the dropdown with directML. Download the onnxgpu-cuda one instead if you want this.

**Comment by JasondaUltima** [comment]
That's the thing, Its not that Im not seeing my GpU In the Drop down Menu  its that there Is No drop down menu at all

And I've tried downloading other versions as well and it doesn't do that, But it doesn't work at all with other versions and No, I was trying to use the Base models that are automatically in the application

**Comment by w-okada** [comment]
This is normal operation. Are you experiencing any problems?

**Comment by w-okada** [comment]
no res close
