### ISSUE TITLE
Pc Requirements.

### ISSUE THREAD

**Issue by rusty65-ai** [w-okada/voice-changer#741]
### Issue Type

Question

### vc client version number

No

### OS

No

### GPU

No

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

SVC - RVC - REAL TIME

### Model type

No

### Situation

Please could you tell me what minimum requirements the pc must have in order to run svc or rvc voice changer in real time? Processor, video card, ram etc!

I'm about to buy a pc, it would be useful for me and for many others to know the minimum requirements for a computer, in order to be able to use your project very well! Thanks in advance for any response from you!

### application window capture

No

### logs on terminal

No

**Comment by Rafacasari** [comment]
I don't think there is a minimum requirement to run the voice changer, it depends on how much you are able to invest. But you don't need a high-end GPU to run the voice changer (it easily runs on my GTX 1080 TI)

My recommendation is a **RTX 3060 12GB GPU**. It can easily run the program with good quality (80 chunks, that give you a fast and good voice) and can also train new voices locally using [RVC WebUI](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI)

A high VRAM GPU is always a good thing for AI training, that's why I reccomend RTX 3060 (12gb)

**Comment by rusty65-ai** [comment]
Thank you Rafa

**Comment by rusty65-ai** [comment]
Thank you Rafa 👍

**Comment by F-pian** [comment]
can I run it on my potato laptop? I only use a 4th generation Intel processor without an external GPU

**Comment by Whitler** [comment]
you can run it with cpu only i think? im not sure... i did run it 1 time with my Core i3-1115G4 on my laptop but it was VERY choppy. and it crashed. (it was running at 3.5gz i think?) then i tried the nvidia mx330 2gb not overclocked (its the gpu for the laptop) but it still was choppy after tweaking. checked the response and it was 20 seconds long (21374ms)

hope this helped
