### ISSUE TITLE
[REQUEST]: Output to File

### ISSUE THREAD

**Issue by spooknik** [w-okada/voice-changer#975]
### In a few words, describe your idea

Output recording to file instead of audio device

### More information

Thank you for the nice software, It works very well for me. 

I would like to request an output to file feature. My usage is to take a prerecorded MP3 and re-record it into a difference voice. (For example, I have an audiobook with bad narrator, I want to change the voice).

**Comment by tempdeltavalue** [comment]
also input from the file doesn't work in my case (I can't even hear input)
![Screenshot 2023-11-01 203902](https://github.com/w-okada/voice-changer/assets/36921178/6e18eada-4833-4da6-98d7-97f440c063e5)

**Comment by gvmii** [comment]
You could do this by using a virtual audio cable and just playing the sound from it. Time consuming but it'd work.

**Comment by w-okada** [comment]
you can record output to file.

![image](https://github.com/w-okada/voice-changer/assets/48346627/58928626-fef8-4bda-9856-0ecf52f6e838)

**Comment by w-okada** [comment]
close

**Comment by Venryx** [comment]
Just wanted to mention a tip: If you want a "one click" way to:
* Start the file playback -> wait for start chunk-delay -> start recording -> wait for input-file play to complete -> wait for end chunk-delay -> stop recording

Then you can use a JS script like the below:
```
function PlayInputAndRecordToFile() {
  const chunkSelectEl = [...document.querySelectorAll(".config-sub-area-control-title")].find(a=>a.innerText == "CHUNK:").nextSibling.childNodes[0];
  const chunkSelectInfo = chunkSelectEl.childNodes[chunkSelectEl.selectedIndex].innerText;
  const chunkDelay = Number(chunkSelectInfo.match(/([0-9.]+) ms/)[1]);
  console.log("ChunkDelay:", chunkDelay);

  const audioInputFileEl = document.querySelector("#audio-test-converted");
  const buttons = [...document.querySelectorAll(".config-sub-area-button, .config-sub-area-button-active")];
  const startRecordButton = buttons[1];
  const stopRecordButton = buttons[2];

  audioInputFileEl.currentTime = 0;
  audioInputFileEl.play();
  setTimeout(()=>startRecordButton.click(), chunkDelay);
  audioInputFileEl.onended = ()=>{
    audioInputFileEl.onended = null;
    setTimeout(()=>stopRecordButton.click(), chunkDelay);
  };
}
PlayInputAndRecordToFile();
```

As usual of course, non-devs should be careful about blindly pasting code into the program's dev-tools (ctrl+shift+i).

But for those who can read through the code above and confirm that it's safe, it is a helpful way to use voice-conversion on lots of files, since it:
* Cuts down on the number of clicks.
* Avoids "extra empty space" at the start and end of the recording. (from inconsistent delay of manually clicking start-recording and stop-recording)

It's be nice if there were a built-in button to do the process above of course, but I'm thankful the program allows for dev-tools access so programmers can make fixes like the above themselves.
